version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: blood
      POSTGRES_PASSWORD: blood
      POSTGRES_DB: bloodbank
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blood"]
      interval: 10s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
    ports: ["9092:9092"]
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 10s
      retries: 5

  inventory-service:
    build: ./services/inventory-service
    depends_on:
      postgres: { condition: service_healthy }
      kafka: { condition: service_healthy }
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bloodbank
      SPRING_DATASOURCE_USERNAME: blood
      SPRING_DATASOURCE_PASSWORD: blood
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    ports: ["8080:8080"]
   
